# Generated by Django 3.1.1 on 2020-10-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(to='Product.Review'),
        ),
    ]
